title:             justiceHui의 개발 블로그
email:             jhnah917@naver.com
description:       justiceHui의 개발 블로그
author:            justiceHui
baseurl:           "/"
url:               "http://justiceHui.github.io"

# Social Profiles
#twitter_username:  
github_username:   justiceHui
#facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
